- name: Enable UFW and deny by default
  ufw:
    state: enabled
    default: deny

- name: Turn on logging
  ufw:
    logging: on

- name: Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow access to tcp port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow access to tcp port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Prevent brute-force SSH login attacks
  ufw:
    rule: limit
    port: 22
    proto: tcp

# https://askubuntu.com/questions/1504520/use-ufw-firewall-to-deny-incoming-ping-icmp-requests
# - name: Drop all echo request ICMP packets


