---
- name: Configure a web server
  hosts: webservers

  vars_files:
    - group_vars/vault.yml

  roles:
    - packages
    - { role: systemd, become: true }
    - { role: sysctl,  become: true }
    - { role: ufw,     become: true }
    - { role: users,   become: true }
    - { role: cron,    become: true }
    - { role: ssh,     become: true }
    - fail2ban
    - nginx

