description: My personal website
author:
  name: Max Besley
  email: besleymax@gmail.com
github_url: https://github.com/maxbesley
linkedin_url: https://linkedin.com/in/max-besley-628531198
goodreads_url: https://goodreads.com/user/show/135018363-max-besley
