---
- name: Set the computer name
  hostname:
    name: webserver
    use: systemd

- name: Enable and start cron
  systemd_service:
    name: cron
    state: started
    enabled: yes

- name: Enable the ssh server
  systemd_service:
    name: ssh
    enabled: yes
    masked: no

