name: Deploy web server Docker image

on:
  push:
    branches: main
    paths:
      - infra/caddy/**
      - Dockerfile
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: webserver

permissions:
  packages: write

jobs:
  build-and-push:
    name: Publish image to ghcr.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set $SHA to the shortened Git commit hash
        run: echo "SHA=$(echo ${GITHUB_SHA} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Add extra labels to image
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}

      - name: Log in to ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.SHA }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-image:
    name: Deploy image to web server
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy Docker image
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker stop $(docker ps -aq)
            docker system prune --force --all
            docker pull ghcr.io/maxbesley/webserver:latest
            docker run --detach --rm --name server -p 443:443 -p 80:80 -v /var/www/personal-website/_site:/srv -v /caddy_data:/data ghcr.io/maxbesley/webserver:latest
